### ISSUE TITLE
Improve in homework №1

### ISSUE THREAD

**Issue by torin4fan** [PivenSergey/Homework#1]
Hi, Sergey!

Thank you for your homework, good job!
I have some imroves for you:

1. Crate second branch like on home task if it possible. It can help improve yor skills with git branches.
2. In `<input>` tag we should use attribute "placeholder" instead "value" for sign place.
3. Your `<button>` -s should looks like:

```
<button type="submit" value="Submit">Отправить</button>
<button type="reset" value="Reset">Сбросить</button>
```

**Comment by PivenSergey** [comment]
Thanks a lot!

**Comment by torin4fan** [comment]
Excellent! Good job.
